### ISSUE TITLE
코드레이드 발표자료 만들기

### ISSUE THREAD

**Issue by fkdl0048** [fkdl0048/ToDo#168]
# 코드레이드 발표자료 만들기

- todo, game ci/cd 내용
- 전 발표자료 참고해서 작성

---

# [Github Action](https://docs.github.com/ko/actions)

코드 레벨(A)의 작업이 아닌 B레벨 정도의 작업을 편리하게 해주는 기능

개인적으로 공부중이고, 활용하고 있어서 공유해보면 좋겠다는 기능이라 들고옴

## 설명

GIthub Actions은 지속적 통합, 지속적 제공(CI/CD) 플랫폼으로 레포에서 일어나는 다양한 이벤트를 자동화할 수 있다.

이외에도 도커, 데이터베이스, 서버와도 연결하여 사용 가능하며 직접적인 수정이 가능하다.

### YAML 파일 기반

YAML파일 형식으로 정의를 생성하고 이를 workflow로 등록시켜 작동하는데 내부에서 cron, job 등 다양한 기능도 사용이 가능하고 실제 opensource 문화도 활발하게 이뤄지고 있다.

![image](https://github.com/fkdl0048/ToDo/assets/84510455/d849279f-43e1-418f-83c9-05004d3d22f1)

작성 방법은 간단하게 설명*실제 사용중인 Action*

```
on:
  schedule:
    - cron: '0 0 * * *'

name: Create an issue on push
permissions:
  contents: read
  issues: write 
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

- on: 워크플로가 실행될 때 트리거되는 이벤트를 정의
  - 현재는 schedule-cron으로 utf 매일 0시 0분에 실행된다.(정확하지 않음)

```
on:
  push:
    branches:
      - main
```

- 이와 같이 이벤트가 push 그리고 브랜치가 main인 경우까지 직관적인 해석이 가능

- permissions: 부여된 기본 권환으로 아래 보이는 `GITHUB_TOKEN`에 설정된 권한급까지만 가능
- jobs: 워크플로 파일에서 실행되는 모든 작업을 그룹화 한다.
- steps: 작업일부로 실행될 모든 단계를 그룹화 한다.

```
      - name: Checkout
        uses: actions/checkout@v3
```

- uses: 지정된 작업을 검색하도록 작업에 지시
- actions/checkout. 이는 리포지토리를 확인하고 러너에 다운로드하여 코드(예: 테스트 도구)에 대해 작업을 실행할 수 있도록 하는 작업이다. 작업 흐름이 저장소의 코드를 사용하거나 저장소에 정의된 작업을 사용할 때마다 체크아웃 작업을 사용해야 한다.

이외에도 정말 다양한 기능이 있으니 궁금하다면 따로 알아볼 것을 추천..

*ex) GameCI*

### 사용 가격

GitHub Actions는 공개 리포지토리에서 무료로 사용할 수 있지만 비공개 리포지토리는 러너의 빌드 시간이 2,000분으로 제한

## 활용 예시: CI/CD

젠킨스?. Teamcity?

이런 CI/CD 프로세스를 많이 사용하고 현업에서는 따로 데브옵스라고 불리며 전문 분야가 있는 작업이 있다.

대부분 작업자가 시간을 들여 빌드, 테스트하기에 시간이 아까워 서버에 가상 VM에 일임하고 결과를 받아보는 방식으로 동작하는데 Github Action을 사용하면 좀 더 효율적으로 사용이 가능하다.

*테스트, 빌드, 배포, 데이터베이스 검증 등등 다양한 작업 가능*

![image](https://github.com/fkdl0048/ToDo/assets/84510455/726bbb90-92d5-48f2-8cb4-8ae5b1aad3e7)

여타 젠킨스나 Teamcity와 다른 점은 직접 수행 과정을 좀 더 세세하게 컨트롤 가능하며 다양한 API와 혼합하여 사용이 가능하다는 점

코드베이스가 깃허브라면 다양한 이벤트 트리거(PR, Issue, Discussion 등)에 붙여서 극한의 자동화까지 갈 수 있다는 점

```
name: GameCI Template 🎮

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
 testRunner:
   name: Test all modes 📝
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Create LFS file list
       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

     - name: Restore LFS cache
       uses: actions/cache@v2
       id: lfs-cache
       with:
         path: .git/lfs
         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

     - name: Git LFS Pull
       run: |
         git lfs pull
         git add .
         git reset --hard

     - name: Restore Library cache
       uses: actions/cache@v2
       with:
         path: Library
         key: Library-test-project
         restore-keys: |
           Library-test-project-
           Library-

     - uses: webbertakken/unity-test-runner@v2
       id: testRunner
       with:
         testMode: all

     - uses: actions/upload-artifact@v2
       with:
         name: Test results (all modes)
         path: ${{ steps.testRunner.outputs.artifactsPath }}

 buildWebGL:
   needs: testRunner
   name: Build for WebGL 🖥️
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Create LFS file list
       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

     - name: Restore LFS cache
       uses: actions/cache@v2
       id: lfs-cache
       with:
         path: .git/lfs
         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

     - name: Git LFS Pull
       run: |
         git lfs pull
         git add .
         git reset --hard

     - name: Restore Library cache
       uses: actions/cache@v2
       with:
         path: Library
         key: Library-build-WebGL
         restore-keys: |
           Library-build-
           Library-

     - uses: webbertakken/unity-builder@v2
       with:
         targetPlatform: WebGL

     - uses: actions/upload-artifact@v2
       with:
         name: build-WebGL
         path: build/WebGL

 buildWindows:
   needs: testRunner
   name: Build for Windows 🖥️
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Create LFS file list
       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

     - name: Restore LFS cache
       uses: actions/cache@v2
       id: lfs-cache
       with:
         path: .git/lfs
         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

     - name: Git LFS Pull
       run: |
         git lfs pull
         git add .
         git reset --hard

     - name: Restore Library cache
       uses: actions/cache@v2
       with:
         path: Library
         key: Library-build-StandaloneWindows64
         restore-keys: |
           Library-build-
           Library-

     - uses: webbertakken/unity-builder@v2
       with:
         targetPlatform: StandaloneWindows64

     - uses: actions/upload-artifact@v2
       with:
         name: build-StandaloneWindows64
         path: build/StandaloneWindows64

 buildAndroid:
   needs: testRunner
   name: Build for Android 📱
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Create LFS file list
       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

     - name: Restore LFS cache
       uses: actions/cache@v2
       id: lfs-cache
       with:
         path: .git/lfs
         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

     - name: Git LFS Pull
       run: |
         git lfs pull
         git add .
         git reset --hard

     - name: Restore Library cache
       uses: actions/cache@v2
       with:
         path: Library
         key: Library-build-Android
         restore-keys: |
           Library-build-
           Library-

     - uses: webbertakken/unity-builder@v2
       with:
         targetPlatform: Android

     - uses: actions/upload-artifact@v2
       with:
         name: build-Android
         path: build/Android


 deployPages:
   needs: buildWebGL
   name: Deploy to Github Pages 🚀
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - uses: actions/download-artifact@v2
       with:
         name: build-WebGL
         path: build

     - name: Display structure of root files
       run: ls -R
       working-directory: build/WebGL

     - name: Deploy 🚀
       uses: JamesIves/github-pages-deploy-action@4.1.4
       with:
         branch: gh-pages
         folder: build/WebGL
```

### 활용 예시: Cron

사소하지만 하루에 반복 설정도 가능하기에 매일 Todo를 관리하거나 생성된 이슈에 대한 트리거가 가능.

## 결론

이미 알고 계시거나 다른 방법을 활용하실 수 있지만 한번 소개해봤습니다..
